/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @constant */
                            status: "ok";
                            app: string;
                            env: string;
                            database: string;
                            time: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: {
                                id: number;
                                name: string;
                                email: string;
                                roles: {
                                    relations: [
                                        "roles"
                                    ];
                                }[];
                                permissions: unknown[];
                            };
                        };
                    };
                };
                401: components["responses"]["AuthenticationException"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/billing-profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["billingProfile.show"];
        put: operations["billingProfile.update"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/clients": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["client.index"];
        put?: never;
        post: operations["client.store"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/clients/{client}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["client.show"];
        put: operations["client.update"];
        post?: never;
        delete: operations["client.destroy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/leads/{lead}/convert": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Turn an enquiry into a client, carrying over what the form already
         *     asked for so the same details are not typed twice
         * @description Idempotent by lead: converting the same enquiry twice returns the
         *     client already made from it rather than creating a duplicate.
         */
        post: operations["client.convertLead"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/clients/{client}/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["document.store"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/documents/{document}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * The whole document, lines included: the editor holds one form, and
         *     sending it a line at a time would let a half-saved invoice exist
         */
        put: operations["document.update"];
        post?: never;
        /**
         * Only drafts. An issued invoice is cancelled, never deleted: the
         *     sequence has to stay whole, and a missing number is a question you
         *     cannot answer a year later
         */
        delete: operations["document.destroy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/documents/{document}/issue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Hand it over: give it its number, freeze who it is from and to, and
         *     stop it being editable
         */
        post: operations["document.issue"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/documents/{document}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Accepted, declined or cancelled — the states that follow issuing */
        post: operations["document.status"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/clients/{client}/engagements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["engagement.store"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/engagements/{engagement}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["engagement.update"];
        post?: never;
        delete: operations["engagement.destroy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/case-study-options": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The case studies an engagement can be linked to. Slim on purpose: the
         *     picker needs a name and an id, not five translated paragraphs
         */
        get: operations["engagement.caseStudyOptions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/leads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Contact form target. Public and therefore rate limited in routes/api.php.
         *     The response deliberately echoes nothing back - there is no reason for a
         *     form post to hand an anonymous caller a database row
         */
        post: operations["lead.store"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/leads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Newest first, optionally narrowed to one status or a search
         * @description The counts ride along with every page so the status tabs stay honest
         *     after a lead moves between them, without a second request.
         */
        get: operations["lead.index"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/leads/{lead}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Opening a lead is what marks it read */
        get: operations["lead.show"];
        put?: never;
        post?: never;
        /** For spam. A real enquiry that went nowhere is marked lost, not deleted */
        delete: operations["lead.destroy"];
        options?: never;
        head?: never;
        patch: operations["lead.update"];
        trace?: never;
    };
    "/v1/admin/documents/{document}/payments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["payment.store"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/payments/{payment}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Returns the invoice, so the dashboard sees the new balance at once */
        delete: operations["payment.destroy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Published case studies */
        get: operations["project.index"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/projects/{project}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["project.show"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["projectMedia.index"];
        put?: never;
        /** A new project starts hidden, with just enough to name it */
        post: operations["projectContent.store"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/projects/{project}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["projectMedia.show"];
        put: operations["projectContent.update"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/projects/{project}/media": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["projectMedia.store"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/media/{media}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["projectMedia.destroy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/services": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Published services, in editor order */
        get: operations["v1.service.index"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/services/{service}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["service.show"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/services": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["v1.admin.service.index"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/services/{service}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["service.update"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Flat key => value map of site copy and contact details */
        get: operations["setting.index"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["setting.show"];
        put: operations["setting.update"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/testimonials": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["testimonial.index"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ClientResource */
        ClientResource: {
            id: number;
            name: string;
            legal_name: string | null;
            ice: string | null;
            contact_name: string | null;
            email: string | null;
            phone: string | null;
            website: string | null;
            address: string | null;
            city: string | null;
            country: string;
            currency: string;
            notes: string | null;
            lead_id: number | null;
            /**
             * @description The work, when the caller asked for it. The client page shows
             *     everything about one client on one screen, so its single
             *     request carries the engagements with it.
             */
            engagements?: components["schemas"]["EngagementResource"][];
            engagements_count?: number;
            documents?: components["schemas"]["DocumentResource"][];
            created_at: string | null;
        };
        /** DocumentItemResource */
        DocumentItemResource: {
            id: number;
            position: number;
            description: string;
            quantity: string;
            unit_price: string;
            total: string;
        };
        /** DocumentResource */
        DocumentResource: {
            id: number;
            client_id: number;
            engagement_id: number | null;
            type: string;
            status: string;
            number: string | null;
            issue_date: string | null;
            due_date: string | null;
            currency: string;
            tva_rate: string;
            subject: string | null;
            notes: string | null;
            terms: string | null;
            items?: components["schemas"]["DocumentItemResource"][];
            payments?: components["schemas"]["PaymentResource"][];
            totals: {
                subtotal: string;
                tva: string;
                total: string;
                paid: string;
                due: string;
            };
            /**
             * @description Worked out here, not stored: "paid" is a fact about the
             *     payments, and a column saying otherwise would be believed.
             */
            settled: string;
            overdue: string;
            editable: boolean;
            created_at: string | null;
        };
        /** EngagementResource */
        EngagementResource: {
            id: number;
            client_id: number;
            title: string;
            status: string;
            /**
             * @description A string, not a float: money read back as a float is money one
             *     rounding away from disagreeing with the invoice.
             */
            budget: string | null;
            starts_on: string | null;
            ends_on: string | null;
            description: string | null;
            case_study_id: number | null;
            case_study?: {
                slug: string;
                title: string;
                is_published: boolean;
            } | null;
            created_at: string | null;
        };
        /** LeadResource */
        LeadResource: {
            id: number;
            name: string;
            email: string;
            phone: string | null;
            company: string | null;
            service_interest: string | null;
            budget_range: string | null;
            message: string;
            note: string | null;
            status: string;
            locale: string;
            source: string | null;
            is_read: boolean;
            /**
             * @description Whether this enquiry already became a client, so the dashboard
             *     can link to them instead of offering to convert a second time.
             */
            client?: {
                id: number;
                name: string;
            } | null;
            created_at: string | null;
        };
        /** MediaResource */
        MediaResource: {
            /** @description The id is what the dashboard deletes by; harmless in public. */
            id: number;
            url: string;
            name: string;
            /**
             * @description Cast explicitly. getCustomProperty() returns mixed, which the
             *     OpenAPI generator could only describe as an empty object — and
             *     that is what the frontend's types then said a width was.
             */
            alt: string | null;
            width: number | null;
            height: number | null;
        };
        /** PaymentResource */
        PaymentResource: {
            id: number;
            amount: string;
            paid_on: string;
            method: string;
            reference: string | null;
        };
        /** ProjectResource */
        ProjectResource: {
            slug: string;
            client_name: string;
            year: number | null;
            project_url: string | null;
            is_featured: boolean;
            title: {
                en: string;
                fr: string;
            };
            summary: {
                en: string;
                fr: string;
            };
            challenge: {
                en: string;
                fr: string;
            };
            solution: {
                en: string;
                fr: string;
            };
            outcome: {
                en: string;
                fr: string;
            };
            tags: string[];
            stack: string[];
            metrics: {
                label: {
                    en: string;
                    fr: string;
                };
                value: string;
            }[];
            cover: components["schemas"]["MediaResource"] | null;
            gallery: components["schemas"]["MediaResource"][];
            dashboard: components["schemas"]["MediaResource"][];
            testimonials?: components["schemas"]["TestimonialResource"][];
            published_at: string | null;
        };
        /** ServiceResource */
        ServiceResource: {
            slug: string;
            title: {
                en: string;
                fr: string;
            };
            tagline: {
                en: string;
                fr: string;
            };
            body: {
                en: string;
                fr: string;
            };
            icon: string | null;
            cover: components["schemas"]["MediaResource"] | null;
        };
        /** StoreLeadRequest */
        StoreLeadRequest: {
            name: string;
            /** Format: email */
            email: string;
            /** @description Required: a number is how these conversations actually start. */
            phone: string;
            company?: string | null;
            budget_range?: string | null;
            service_interest?: string | null;
            message: string;
            /** @enum {string|null} */
            locale?: "en" | "fr" | null;
            source?: string | null;
        };
        /** TestimonialResource */
        TestimonialResource: {
            id: number;
            author_name: string;
            author_role: string | null;
            client_name: string | null;
            quote: {
                en: string;
                fr: string;
            };
            avatar: components["schemas"]["MediaResource"] | null;
            project_slug?: string | null;
        };
    };
    responses: {
        /** @description Not found */
        ModelNotFoundException: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    /** @description Error overview. */
                    message: string;
                };
            };
        };
        /** @description Validation error */
        ValidationException: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    /** @description Errors overview. */
                    message: string;
                    /** @description A detailed description of each field that failed validation. */
                    errors: {
                        [key: string]: string[];
                    };
                };
            };
        };
        /** @description Unauthenticated */
        AuthenticationException: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    /** @description Error overview. */
                    message: string;
                };
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    "billingProfile.show": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            [key: string]: unknown;
                        };
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "billingProfile.update": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name: string;
                    /** Format: email */
                    email?: string | null;
                    phone?: string | null;
                    tva_rate: number;
                    payment_terms?: string | null;
                    footer_note?: string | null;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            [key: string]: unknown;
                        };
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "client.index": {
        parameters: {
            query?: {
                q?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated set of `ClientResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["ClientResource"][];
                        links: {
                            first: string | null;
                            last: string | null;
                            prev: string | null;
                            next: string | null;
                        };
                        meta: {
                            current_page: number;
                            from: number | null;
                            last_page: number;
                            /** @description Generated paginator links. */
                            links: {
                                url: string | null;
                                label: string;
                                active: boolean;
                            }[];
                            /** @description Base path for paginator generated URLs. */
                            path: string | null;
                            /** @description Number of items shown per page. */
                            per_page: number;
                            /** @description Number of the last item in the slice. */
                            to: number | null;
                            /** @description Total number of items being paginated. */
                            total: number;
                        };
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "client.store": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name: string;
                    legal_name?: string | null;
                    /**
                     * @description Morocco's ICE is 15 digits. Loose enough for a foreign client's
                     *     equivalent, strict enough to catch a pasted phone number.
                     */
                    ice?: string | null;
                    contact_name?: string | null;
                    /** Format: email */
                    email?: string | null;
                    phone?: string | null;
                    /** Format: uri */
                    website?: string | null;
                    address?: string | null;
                    city?: string | null;
                    country: string;
                    currency: string;
                    notes?: string | null;
                };
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["ClientResource"];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "client.show": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The client ID */
                client: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description `ClientResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["ClientResource"] & Record<string, never>;
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            404: components["responses"]["ModelNotFoundException"];
        };
    };
    "client.update": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The client ID */
                client: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name: string;
                    legal_name?: string | null;
                    /**
                     * @description Morocco's ICE is 15 digits. Loose enough for a foreign client's
                     *     equivalent, strict enough to catch a pasted phone number.
                     */
                    ice?: string | null;
                    contact_name?: string | null;
                    /** Format: email */
                    email?: string | null;
                    phone?: string | null;
                    /** Format: uri */
                    website?: string | null;
                    address?: string | null;
                    city?: string | null;
                    country: string;
                    currency: string;
                    notes?: string | null;
                };
            };
        };
        responses: {
            /** @description `ClientResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["ClientResource"];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            404: components["responses"]["ModelNotFoundException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "client.destroy": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The client ID */
                client: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["AuthenticationException"];
            404: components["responses"]["ModelNotFoundException"];
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        message: "This client has quotes or invoices. They have to stay, so the client does too.";
                    };
                };
            };
        };
    };
    "client.convertLead": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The lead ID */
                lead: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["ClientResource"];
                    };
                };
            };
            /**
             * @description Refreshed before serialising: country and currency come from column
             *     defaults, which the freshly built model has never read, so without
             *     this the dashboard is handed empty strings for both — and saving
             *     that form would write the blanks back over the real values.
             */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["ClientResource"];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            404: components["responses"]["ModelNotFoundException"];
        };
    };
    "document.store": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The client ID */
                client: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @enum {string} */
                    type: "quote" | "invoice";
                    engagement_id?: number | null;
                    /**
                     * @description A 50/50 build is the usual arrangement, so the two halves are
                     *     one click rather than arithmetic done twice.
                     * @enum {string|null}
                     */
                    preset?: "deposit" | "balance" | "full" | null;
                };
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["DocumentResource"] & Record<string, never>;
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            404: components["responses"]["ModelNotFoundException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "document.update": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The document ID */
                document: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    engagement_id?: number | null;
                    /** Format: date-time */
                    issue_date?: string | null;
                    /** Format: date-time */
                    due_date?: string | null;
                    tva_rate: number;
                    subject?: string | null;
                    notes?: string | null;
                    terms?: string | null;
                    items: {
                        description: string;
                        quantity: number;
                        unit_price: number;
                    }[];
                };
            };
        };
        responses: {
            /** @description `DocumentResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["DocumentResource"] & Record<string, never>;
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            404: components["responses"]["ModelNotFoundException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "document.destroy": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The document ID */
                document: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["AuthenticationException"];
            404: components["responses"]["ModelNotFoundException"];
        };
    };
    "document.issue": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The document ID */
                document: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description `DocumentResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["DocumentResource"] & Record<string, never>;
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            404: components["responses"]["ModelNotFoundException"];
        };
    };
    "document.status": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The document ID */
                document: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @enum {string} */
                    status: "sent" | "accepted" | "declined" | "cancelled";
                };
            };
        };
        responses: {
            /** @description `DocumentResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["DocumentResource"] & Record<string, never>;
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            404: components["responses"]["ModelNotFoundException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "engagement.store": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The client ID */
                client: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    title: string;
                    /** @enum {string} */
                    status: "planned" | "active" | "paused" | "done" | "cancelled";
                    /**
                     * @description Kept as a string through validation so 12000.50 is checked as
                     *     written rather than after a float has had its say.
                     */
                    budget?: number | null;
                    /** Format: date-time */
                    starts_on?: string | null;
                    /** Format: date-time */
                    ends_on?: string | null;
                    description?: string | null;
                    case_study_id?: number | null;
                };
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["EngagementResource"] & Record<string, never>;
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            404: components["responses"]["ModelNotFoundException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "engagement.update": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The engagement ID */
                engagement: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    title: string;
                    /** @enum {string} */
                    status: "planned" | "active" | "paused" | "done" | "cancelled";
                    /**
                     * @description Kept as a string through validation so 12000.50 is checked as
                     *     written rather than after a float has had its say.
                     */
                    budget?: number | null;
                    /** Format: date-time */
                    starts_on?: string | null;
                    /** Format: date-time */
                    ends_on?: string | null;
                    description?: string | null;
                    case_study_id?: number | null;
                };
            };
        };
        responses: {
            /** @description `EngagementResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["EngagementResource"] & Record<string, never>;
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            404: components["responses"]["ModelNotFoundException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "engagement.destroy": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The engagement ID */
                engagement: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["AuthenticationException"];
            404: components["responses"]["ModelNotFoundException"];
        };
    };
    "engagement.caseStudyOptions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            id: number;
                            slug: string;
                            title: string;
                            is_published: boolean;
                        }[];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "lead.store": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StoreLeadRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        message: "Thanks - we will be in touch shortly.";
                    };
                };
            };
            422: components["responses"]["ValidationException"];
        };
    };
    "lead.index": {
        parameters: {
            query?: {
                status?: "new" | "contacted" | "quoted" | "won" | "lost" | null;
                q?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated set of `LeadResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: (components["schemas"]["LeadResource"] & Record<string, never>)[];
                        links: {
                            first: string | null;
                            last: string | null;
                            prev: string | null;
                            next: string | null;
                        };
                        meta: {
                            current_page: number;
                            from: number | null;
                            last_page: number;
                            /** @description Generated paginator links. */
                            links: {
                                url: string | null;
                                label: string;
                                active: boolean;
                            }[];
                            /** @description Base path for paginator generated URLs. */
                            path: string | null;
                            /** @description Number of items shown per page. */
                            per_page: number;
                            /** @description Number of the last item in the slice. */
                            to: number | null;
                            /** @description Total number of items being paginated. */
                            total: number;
                            counts: string[];
                            unread: number;
                        };
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "lead.show": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The lead ID */
                lead: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description `LeadResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["LeadResource"] & Record<string, never>;
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            404: components["responses"]["ModelNotFoundException"];
        };
    };
    "lead.destroy": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The lead ID */
                lead: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["AuthenticationException"];
            404: components["responses"]["ModelNotFoundException"];
        };
    };
    "lead.update": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The lead ID */
                lead: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /** @enum {string} */
                    status?: "new" | "contacted" | "quoted" | "won" | "lost";
                    note?: string | null;
                    is_read?: boolean;
                };
            };
        };
        responses: {
            /** @description `LeadResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["LeadResource"] & Record<string, never>;
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            404: components["responses"]["ModelNotFoundException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "payment.store": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The document ID */
                document: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    amount: number;
                    /** Format: date-time */
                    paid_on: string;
                    /** @enum {string} */
                    method: "transfer" | "cheque" | "cash" | "card" | "other";
                    reference?: string | null;
                };
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["DocumentResource"] & Record<string, never>;
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            404: components["responses"]["ModelNotFoundException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "payment.destroy": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The payment ID */
                payment: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["DocumentResource"] & Record<string, never>;
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            404: components["responses"]["ModelNotFoundException"];
        };
    };
    "project.index": {
        parameters: {
            query?: {
                featured?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Array of `ProjectResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["ProjectResource"][];
                    };
                };
            };
        };
    };
    "project.show": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The project slug */
                project: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description `ProjectResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["ProjectResource"] & Record<string, never>;
                    };
                };
            };
            404: components["responses"]["ModelNotFoundException"];
        };
    };
    "projectMedia.index": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            slug: string;
                            client_name: string;
                            title: {
                                en: string;
                                fr: string;
                            };
                            year: number | null;
                            is_published: boolean;
                            is_featured: boolean;
                            cover: components["schemas"]["MediaResource"];
                            counts: {
                                gallery: number;
                                dashboard: number;
                            };
                        }[];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "projectContent.store": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    client_name: string;
                    title_en: string;
                    slug?: string | null;
                };
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            slug: string;
                            client_name: string;
                            title: {
                                en: string;
                                fr: string;
                            };
                            year: number | null;
                            is_published: boolean;
                            is_featured: boolean;
                            cover: components["schemas"]["MediaResource"];
                            counts: {
                                gallery: number;
                                dashboard: number;
                            };
                            project_url: string | null;
                            position: number;
                            is_live: boolean;
                            summary: {
                                en: string;
                                fr: string;
                            };
                            challenge: {
                                en: string;
                                fr: string;
                            };
                            solution: {
                                en: string;
                                fr: string;
                            };
                            outcome: {
                                en: string;
                                fr: string;
                            };
                            tags: unknown[];
                            metrics: unknown[];
                            gallery: components["schemas"]["MediaResource"][];
                            dashboard: components["schemas"]["MediaResource"][];
                        };
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "projectMedia.show": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The project slug */
                project: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            slug: string;
                            client_name: string;
                            title: {
                                en: string;
                                fr: string;
                            };
                            year: number | null;
                            is_published: boolean;
                            is_featured: boolean;
                            cover: components["schemas"]["MediaResource"];
                            counts: {
                                gallery: number;
                                dashboard: number;
                            };
                            project_url: string | null;
                            position: number;
                            is_live: boolean;
                            summary: {
                                en: string;
                                fr: string;
                            };
                            challenge: {
                                en: string;
                                fr: string;
                            };
                            solution: {
                                en: string;
                                fr: string;
                            };
                            outcome: {
                                en: string;
                                fr: string;
                            };
                            tags: unknown[];
                            metrics: unknown[];
                            gallery: components["schemas"]["MediaResource"][];
                            dashboard: components["schemas"]["MediaResource"][];
                        };
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            404: components["responses"]["ModelNotFoundException"];
        };
    };
    "projectContent.update": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The project slug */
                project: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            slug: string;
                            client_name: string;
                            title: {
                                en: string;
                                fr: string;
                            };
                            year: number | null;
                            is_published: boolean;
                            is_featured: boolean;
                            cover: components["schemas"]["MediaResource"];
                            counts: {
                                gallery: number;
                                dashboard: number;
                            };
                            project_url: string | null;
                            position: number;
                            is_live: boolean;
                            summary: {
                                en: string;
                                fr: string;
                            };
                            challenge: {
                                en: string;
                                fr: string;
                            };
                            solution: {
                                en: string;
                                fr: string;
                            };
                            outcome: {
                                en: string;
                                fr: string;
                            };
                            tags: unknown[];
                            metrics: unknown[];
                            gallery: components["schemas"]["MediaResource"][];
                            dashboard: components["schemas"]["MediaResource"][];
                        };
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            404: components["responses"]["ModelNotFoundException"];
        };
    };
    "projectMedia.store": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The project slug */
                project: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    collection: string;
                    /**
                     * Format: binary
                     * @description Checked by content, not by the name the browser sent: `image`
                     *     and `mimes` both sniff the file itself, so a script renamed to
                     *     .jpg is refused. No SVG — it can carry script, and it would be
                     *     served from our own CDN domain.
                     */
                    file: string;
                    alt?: string | null;
                };
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["MediaResource"];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            404: components["responses"]["ModelNotFoundException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "projectMedia.destroy": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The media ID */
                media: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: null;
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            404: components["responses"]["ModelNotFoundException"];
        };
    };
    "v1.service.index": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Array of `ServiceResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["ServiceResource"][];
                    };
                };
            };
        };
    };
    "service.show": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The service slug */
                service: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description `ServiceResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["ServiceResource"];
                    };
                };
            };
            404: components["responses"]["ModelNotFoundException"];
        };
    };
    "v1.admin.service.index": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            slug: string;
                            position: number;
                            is_published: boolean;
                            title: {
                                en: string;
                                fr: string;
                            };
                            tagline: {
                                en: string;
                                fr: string;
                            };
                            body: {
                                en: string;
                                fr: string;
                            };
                        }[];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "service.update": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The service slug */
                service: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    is_published: boolean;
                    position: number;
                    title: {
                        en: string;
                        fr: string;
                    };
                    tagline: {
                        en: string;
                        fr: string;
                    };
                    body?: {
                        en?: string | null;
                        fr?: string | null;
                    };
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            slug: string;
                            position: number;
                            is_published: boolean;
                            title: {
                                en: string;
                                fr: string;
                            };
                            tagline: {
                                en: string;
                                fr: string;
                            };
                            body: {
                                en: string;
                                fr: string;
                            };
                        };
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            404: components["responses"]["ModelNotFoundException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "setting.index": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            [key: string]: unknown;
                        };
                    };
                };
            };
        };
    };
    "setting.show": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            hero_headline: {
                                en: string;
                                fr: string;
                            };
                            hero_body: {
                                en: string;
                                fr: string;
                            };
                            contact_email: string;
                            contact_phone: string;
                            contact_location: string;
                        };
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "setting.update": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    hero_headline: {
                        en: string;
                        fr: string;
                    };
                    hero_body: {
                        en: string;
                        fr: string;
                    };
                    /** Format: email */
                    contact_email: string;
                    contact_phone?: string | null;
                    contact_location?: string | null;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            hero_headline: {
                                en: string;
                                fr: string;
                            };
                            hero_body: {
                                en: string;
                                fr: string;
                            };
                            contact_email: string;
                            contact_phone: string;
                            contact_location: string;
                        };
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "testimonial.index": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Array of `TestimonialResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: (components["schemas"]["TestimonialResource"] & Record<string, never>)[];
                    };
                };
            };
        };
    };
}
